# Generated by Django 4.1.10 on 2023-07-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitapSepeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('site', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('numberof_pages', models.CharField(max_length=10)),
                ('isbn', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('book_cover', models.CharField(max_length=20)),
                ('paper_type', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kitapsepeti',
            },
        ),
        migrations.CreateModel(
            name='KitapYurdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('site', models.CharField(max_length=50)),
                ('numberof_pages', models.CharField(max_length=10)),
                ('isbn', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('book_cover', models.CharField(max_length=20)),
                ('paper_type', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kitapyurdu',
            },
        ),
    ]
