# Generated by Django 4.1.10 on 2023-07-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('yayıncı', models.CharField(max_length=100)),
                ('yazar', models.CharField(max_length=100)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('site', models.CharField(max_length=50)),
                ('Türü', models.CharField(max_length=50)),
                ('Sayfa_Sayısı', models.CharField(max_length=10)),
                ('ISBN', models.CharField(max_length=20)),
                ('Boyut', models.CharField(max_length=20)),
                ('Kapak', models.CharField(max_length=20)),
                ('Kağıt_Tipi', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
