# Generated by Django 4.1.10 on 2023-07-23 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitapsepeti',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
