# Generated by Django 4.1.10 on 2023-07-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingapi', '0002_book_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Kağıt_Tipi',
            new_name='KağıtTipi',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Sayfa_Sayısı',
            new_name='SayfaSayısı',
        ),
    ]
