# Generated by Django 4.1.10 on 2023-07-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingapi', '0003_rename_kağıt_tipi_book_kağıttipi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='KağıtTipi',
            new_name='KagitTipi',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='SayfaSayısı',
            new_name='SayfaSayisi',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='yayıncı',
            new_name='yayinci',
        ),
    ]
