# Generated by Django 4.1.10 on 2023-07-23 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingapi', '0003_alter_kitapyurdu_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitapsepeti',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 23, 16, 33, 46, 885279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='kitapyurdu',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 23, 16, 33, 46, 885279, tzinfo=datetime.timezone.utc)),
        ),
    ]
