# Generated by Django 4.1.10 on 2023-07-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingapi', '0004_rename_kağıttipi_book_kagittipi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Türü',
            new_name='Turu',
        ),
    ]
