# Generated by Django 4.1.10 on 2023-07-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingapi', '0007_alter_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Boyut',
            new_name='book_cover',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='isim',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='SayfaSayisi',
            new_name='numberof_pages',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='KagitTipi',
            new_name='paper_type',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='fiyat',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='yayinci',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Kapak',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Turu',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='yazar',
            new_name='writer',
        ),
    ]
